Fixed shortcut collision on mac
krassowski/Anki-Night-Mode pull request #43
Opened 2018-08-10 04:54 UTC by Spirarel

On macOS, "ctrl+n" is actually rendered "cmd+n", so it conflicted with the shortcut to change note types within the add card window.

2018-08-10 08:02 UTC, krassowski commented
Thanks for bringing this up. However, changing the shortcut unconditionally would break the experience for many of existing users. In addition, `Alt +  n` is used to insert dialectic characters in many languages, for example, in my native Polish (it inserts `ń`).

We might want to allow users to set their own shortcut instead, or set a different one for Mac conditionally.

2018-08-10 16:30 UTC, Spirarel commented
No worries, I figured an issue report might be more appropriate, but I had already made the change locally...

I think a user-configurable shortcut would be good, but if the add-on is to be adopted by mac users, it will need a better default. This, of course, assuming my experience is the common one.

2018-08-10 17:47 UTC, krassowski commented
Well, you are the first one to raise this issue since the add-on was created three years ago ;)

2019-07-23 15:37 UTC, krassowski requested changes
As mentioned in the discussion, this would have to be implemented as a customizable option or conditionally on the OS, as we cannot just break the experience for all the current users who are used to <kbd>Ctrl</kbd> + <kbd>n</kbd> shortcut.

2020-05-11 19:32 UTC, krassowski commented
Closing as no one was interested to follow up on this for over a year and a half.

2020-05-11 19:32 UTC, closed without merging